### ISSUE TITLE
FirebasePlugin

### ISSUE THREAD

**Issue by andrapascu** [dpa99c/cordova-plugin-firebase#13]
Hi,
window.FirebasePlugin is undefined...

Can you help me?

**Comment by dpa99c** [comment]
That's not sufficient information to open an issue.

Please cloning and building [the example project](https://github.com/dpa99c/cordova-plugin-firebase-test) as a working reference.

**Comment by adamdupuis** [comment]
I am also having this problem. I wait until the `deviceready` event before waiting in a `setTimeout` for `window.FirebasePlugin` to be defined, but it never is. I'm thinking I'm missing something or my `google-services.json` is in the wrong location. I have it in both the cordova project root and in `www` as that is where it is in your example project.

I also tried installing `cordova-support-google-services` but that didn't seem to help.

**Comment by adamdupuis** [comment]
I've figured it out. I was using PhoneGap and it only supports cli-8.1.1, not 9.0.0. When installing the plugin I missed that it was skipping `cordova-plugin-firebasex` because it requires >=9.0.0 so it was never properly installed, hence the `undefined` error.

Solution is to use Cordova instead of PhoneGap.
