### ISSUE TITLE
Firebasex plugin not working with googleplus plugin

### ISSUE THREAD

**Issue by mogupta** [dpa99c/cordova-plugin-firebase#31]
**Describe the bug**
I am having trouble building the IOS app . I kept my original project aside and tried the following ionic google plus project. https://github.com/ionicthemes/ionic-google-login
On running the  project, it works out of the box. Google signin works and build is also successful. but as soon as I add this plugin I get the following errors.

``
The following build commands failed:
	Ld /Users/mohit-mac/Library/Developer/Xcode/DerivedData/ionic4-google-login-azcneaftnwzvrrdylefkgrhrlrsu/Build/Intermediates.noindex/ArchiveIntermediates/ionic4-google-login/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/nanopb.build/Objects-normal/armv7/nanopb normal armv7
(1 failure)
``

When I run the app using xcode and click on google signin, it throws the following error on xcode console

``
2019-07-03 09:04:03.982233+0530 ionic4-google-login[1072:205254] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryI gtm_httpArgumentsString]: unrecognized selector sent to instance 0x280333800'
*** First throw call stack:
(0x19171127c 0x1908eb9f8 0x19162dab8 0x191716ac4 0x19171875c 0x1007f3a20 0x1007f5888 0x1007f52e8 0x1005428bc 0x1005424b0 0x1007bf800 0x10054bdc0 0x10054bc28 0x10054f440 0x1a0d2ce54 0x1a0e90378 0x1a0ffb980 0x1a0c1de44 0x1a0ddd930 0x1a0c0e9b4 0x1a0c114a4 0x19885a310 0x19885a5d0 0x1916a3018 0x1916a2f98 0x1916a2880 0x19169d7bc 0x19169d0b0 0x19389d79c 0x1bded3978 0x100539110 0x1911628e0)
libc++abi.dylib: terminating with uncaught exception of type NSException
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.
(lldb) 
``
**To Reproduce**
1. clone https://github.com/ionicthemes/ionic-google-login
2. run the project, it works flawlessly
3. cordova plugin add cordova-plugin-firebasex
4. cordova run ios 
5. See error
also I am able to run the project on xcode, after it fails to run on cordova cli . The app runs but it crashes  on ``signIn.clientID = clientId``
**Expected behavior**
It should build fine

**Screenshots**

**Console Logs**
If applicable, provide console logs showing the errors being reported.

**Plugin Version**
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-cocoapod-supportx 1.7.3 "Cordova CocoaPods Dependency Support"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-firebasex 3.0.8 "Google Firebase Plugin"
cordova-plugin-googleplus 5.3.2 "Google SignIn"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.5.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"

**Desktop (please complete the following information):**
 - OS: Mac Mojave
 - Browser chrome

**Smartphone (please complete the following information):**
 - Device: Iphone 6
 - OS: 12.3.1

**Additional context**
Ionic:

   ionic (Ionic CLI)             : 4.9.0 (/Users/mohit-mac/.nvm/versions/node/v8.11.4/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.0.7
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.5.1, (and 9 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v8.11.4 (/Users/mohit-mac/.nvm/versions/node/v8.11.4/bin/node)
   npm        : 6.7.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001

**Comment by mogupta** [comment]
I have tried this also
https://stackoverflow.com/questions/56185845/unrecognized-selector-sent-to-instance-ionic-cordova-google-plus-login

**Comment by dpa99c** [comment]
[cordova-plugin-googleplus](https://github.com/EddyVerbruggen/cordova-plugin-googleplus) includes a [static snapshot](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/blob/master/plugin.xml#L91) of the GoogleUtilities library (as well as other Google libraries) [as an Xcode framework](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/tree/master/src/ios/libs) rather than including it dynamically via Cocopods.

The version it bundles is over 3 years old and hence far out of date. 
This plugin currently depends on Firebase SDK v6.3.0 for iOS which is added dynamically via Cocopods.
That in turn pulls in Google Utilities v6.2.0 - a much more recent version and hence the iOS build fails due to 2 incompatible versions of the library being included.

The solution mentioned in the SO post will not work since it recommends bumping the Cocopods version but `cordova-plugin-googleplus` does not use Cocopods.

Issues have been raised against `cordova-plugin-googleplus` e.g. [#553](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/553) due to this.

Therefore if you wish to use `cordova-plugin-googleplus` in the same build as this plugin, `cordova-plugin-googleplus` will need updating to use newer versions of the Google libraries, preferably syndicated by Cocopods.

Since this plugin is not at fault, this issue will now be closed.
