### ISSUE TITLE
Ionic Native Plugin Non Compatibility Due to Name Change

### ISSUE THREAD

**Issue by hcassar93** [dpa99c/cordova-plugin-firebase#38]
**Describe the bug**
Thanks very much for this fork. Worked like a charm first time I used it :)

Unfortunately now that the name of the plugin has changed 'cordova-plugin-firebase' - 'cordova-plugin-firebasex' the ionic native wrapper no longer finds the plugin for me.

Thus, while the app builds fine, on loading it throws the error cant find plugin. Because its looking for 'cordova-plugin-firebase' then fails to work.

I have tried to compensate for this myself but lack a sufficient understanding of how ionic native works to change the references to the new name. It seems others have had this issue too.  

https://github.com/ionic-team/ionic-native/issues/3038 

Is there a way to make this fork accessible to ionic native? Or will we have to wait for ionic native to change to a new plugin which is doubtful?

Thanks for any help you can provide.

Regards
Hayden

**Comment by dpa99c** [comment]
Your options are:

1. Use this forked plugin directly via its Javascript API (vs Ionic Native Typescript API), e.g.

```
window['FirebasePlugin'].onTokenRefresh((token) => {
    console.log("Token refreshed: " + token);
}, (error) => {
    console.error("Failed to refresh token: " + error);
});
```    

2. Locally hack the Ionic Native plugin configuation in `node_modules/@ionic-native/firebase/` - search and replace any references to `cordova-plugin-firebase` with `cordova-plugin-firebasex`

3. Raise an issue against Ionic Native

**Comment by T-moz** [comment]
@dpa99c I just tried the first option you propose and it's not working. I can build my application, but the token is not refreh, and i don't recieve notification.

**Comment by T-moz** [comment]
How exactly window['FirebasePlugin'] is working ?

**Comment by dpa99c** [comment]
This plugin [exposes its API](https://github.com/dpa99c/cordova-plugin-firebase/blob/master/plugin.xml#L22) as `FirebasePlugin`  in the global Javascript namespace.

So from JS you'd reference it as `window.FirebasePlugin`, e.g. `window.FirebasePlugin.onTokenRefresh()`.

But since Ionic is Typescript-based, `window.FirebasePlugin` will raise a lint error because `FirebasePlugin` is not a defined property of the `window` object. 
So by referencing the key as a string (`window['FirebasePlugin']`), it passes Typescript validation and allows you to reference the plugin's JS API directly.

For a working reference illustrating this plugin's usage, see the [example project](https://github.com/dpa99c/cordova-plugin-firebase-test) which [references the JS API directly](https://github.com/dpa99c/cordova-plugin-firebase-test/blob/master/www/js/index.js#L17)

**Comment by T-moz** [comment]
@dpa99c Thank you, i going to take a look !
