### ISSUE TITLE
No data send to Firebase Crashlytics

### ISSUE THREAD

**Issue by fpb16** [dpa99c/cordova-plugin-firebase#40]
**What happen**

After set FirebasePlugin.logMessage("my message")  FirebasePlugin.logError(nameError) and 
create an error in my code to test crash report on Crashlytics Dashboard in Firebase, I build successfully and test on a phone  my app and when the error arrives it appears in the console (  via a console.log ) but logMessage and logError doesn't react and send nothing to Firebase Crashlytics. 
FirebasePlugin is defined, logMessage and logError are existing function. 

Did i miss something when I was setting Crashlytics or not ? 

The app is tested on Android , and I have already google-services.json on my project.
I have set Firebase Analytics already and it works perfectly fine. 

**Plugin Version**
cordova : 8.1.2
firebase : cordova-plugin-firebasex  & cordova-plugin-androidx-adapter

**Comment by dpa99c** [comment]
On Android you currently will only see the log output appear in the Firebase Console.

`logError()` sends the message right away:

![console android](https://user-images.githubusercontent.com/2345062/61072198-b3855a00-a40a-11e9-9767-ee91f44ab7ca.jpg)

`logMessage()` only sends the message along with the next crash:

![logcat](https://user-images.githubusercontent.com/2345062/61072082-77ea9000-a40a-11e9-94bb-a63f9426450a.jpg)

![console android crash](https://user-images.githubusercontent.com/2345062/61072136-9486c800-a40a-11e9-851d-3af4782bf2a9.jpg)


See the [Crashlytics docs for Android for details](https://docs.fabric.io/android/crashlytics/enhanced-reports.html?#custom-logging).

However I will improve the Android implementation in the next version so it also logs to the native logcat output.


On iOS, the plugin uses the `CLSNSLog` which logs data to the Xcode console as well as to the remote Crashlytics service.
Both `logError()` and `logMessage()` only send along with the next crash dump:

![Screenshot 2019-07-11 at 16 57 13](https://user-images.githubusercontent.com/2345062/61072760-e1b76980-a40b-11e9-93e1-9eaf5207c187.png)

![ios console](https://user-images.githubusercontent.com/2345062/61072805-f693fd00-a40b-11e9-8929-0848b18a8769.jpg)

Note: in an iOS debug build you may need to [upload the dSYM](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?authuser=0) in order to see you crash data appear in the Firebase Console.

See the [Crashlytics docs for iOS for details](https://docs.fabric.io/apple/crashlytics/enhanced-reports.html#custom-logs).

You can call `FirebasePlugin.sendCrash()` to force a crash - [see here](https://firebase.google.com/docs/crashlytics/force-a-crash?authuser=0#force_a_crash_to_test_your_implementation) for details on crash testing.

**Comment by mvergarair** [comment]
Hey Dave, I have a question about this: in the firebase crashlytics console I'm only getting one issue:
![image](https://user-images.githubusercontent.com/12487670/67793764-384bc080-fa5a-11e9-9e2a-9b3e913bcecb.png)
All the non-fatal exceptions are being grouped into one issue, is there anyway to separate these issues?
